const ERR_CODE_UNAUTHORIZED = 401;
const ERR_CODE_BAD_REQUEST = 400;
const ERR_CODE_CONFLICT = 409;
const ERR_CODE_FORBIDDEN = 403;
const ERR_CODE_NOT_FOUND = 404;

module.exports = {
  ERR_CODE_UNAUTHORIZED,
  ERR_CODE_BAD_REQUEST,
  ERR_CODE_CONFLICT,
  ERR_CODE_FORBIDDEN,
  ERR_CODE_NOT_FOUND,
};
